plugin: aws_ec2
regions:
  - ap-south-1
filters:
  tag:Name: MyEC2Instance    # EC2 instance must have this tag
keyed_groups:
  - key: tags.Name
    prefix: tag_Name_
hostnames:
  - public-ip-address
