name: Terraform EC2 Provisioning

on:
  push:

jobs:
  terraform:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init and Apply
        run: |
          terraform init
          terraform apply -auto-approve
